## Query to ask the Game of Thrones character database who is dead (and who killed them):

## The following commands should be run in the terminal as a root before running this script:

## rdf=GoT.rdf
## uri=http://localhost:8000/data/http://biobeat.org/data/$rdf
## curl -X DELETE $uri
## curl -T $rdf -H 'Content-Type: application/x-turtle' $uri

## This is how to run this script (as a normal user):

## cat GoT_query.rq |sparql-query "http://localhost:8000/sparql/" -p 


SELECT ?id ?Killer
WHERE
{
  ?id   <http://biobeat.org/rdf/ns#Status>    "Dead".
  ?id   <http://biobeat.org/rdf/ns#Killer>    ?Killer.
}



